{
 "title": "HomeLab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  kube_pod_container_status_ready\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace, pod) (\n  kube_pod_container_info\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))\n* on(instance) group_left(nodename)\nnode_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Kubernetes Node Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(\n  (\n    1 -\n    (\n      node_memory_MemAvailable_bytes\n      /\n      node_memory_MemTotal_bytes\n    )\n  ) * 100\n)\n* on(instance) group_left(nodename)\nnode_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(\n  (\n    1 -\n    (\n      node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}\n      /\n      node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\n    )\n  ) * 100\n)\n* on(instance) group_left(nodename)\nnode_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}