---
- name: Test Grafana API
  hosts: localhost
  connection: local

  vars_files:
    - ../group_vars/all/secrets.yml

  tasks:
    - name: Get Grafana health
      ansible.builtin.uri:
        url: http://localhost:3000/api/health
        method: GET
        user: admin
        password: "{{ grafana_password }}"
        force_basic_auth: true
        return_content: true
      register: grafana_health

    - name: Show Grafana response
      ansible.builtin.debug:
        var: grafana_health.json
